### ISSUE TITLE
✅ [24.01.02] 메인 페이지 세미폴리오 컴포넌트 구현

### ISSUE THREAD

**Issue by cmkoi1** [9weeks-app-web/Team-8#13]
## Todo
- [x] 세미폴리오 컴포넌트 구현
- [x] 더미 데이터로 map
- [x] key 값 생성하여 해당 값에 맞는 모달 창 구현
