### ISSUE TITLE
✅ [23.12.28] Vite 세팅

### ISSUE THREAD

**Issue by s-ja** [9weeks-app-web/Team-8#3]
## Todo
- [x] 프로젝트 Vite 로 전환, 설치
- [x] 기타 필요 라이브러리 설치
- [x] 프로젝트 기본 뼈대 설정
