### ISSUE TITLE
✅ [24.01.10] 필터링 기능, 모달창 디자인

### ISSUE THREAD

**Issue by cmkoi1** [9weeks-app-web/Team-8#55]
## 작업 사항

필터링 기능, 모달창 디자인

## Todo
- [ ] 목데이터 받아와서 입력
- [ ] 필터링 기능 구현
- [ ] 모달창 디자인 작업
