### ISSUE TITLE
✅ [24.01.02] 라우터 및 초기 세팅

### ISSUE THREAD

**Issue by s-ja** [9weeks-app-web/Team-8#8]
## Todo
- [ ] 로그인, 회원가입 페이지에 제거된 헤더 추가 작업
  - 라우팅 구조 수정 
- [ ] 필요 페이지 라우터 세팅
- [ ] 컴포넌트 구분 및 배치를 위한 폴더 및 파일 생성
